### PR TITLE
Changing submodule reference to use new repo

### PR DESCRIPTION
**Pull request by erikbosch**
Use proto files from kuksa-databroker instead of kuksa.val

_This should not make any practical difference as the files as of today should be identical_

### CODE REVIEW

**Comment by erikbosch** [comment]
Hmm, noticed that test fails as 

- Kuksa Server JWTs does not exist in kuksa-databroker or kuksa-common
- Kuksa TLS certs exists in kuksa-common, but we have previously discussed if we should remove them as "default"

We have said that KUKSA Server shall reach EoL 2024-12-31, but we have not yet said when we should remove KUKSA Server support from kuksa-client. I see some options:

- Remove default certs/tokens from kuksa-client. This we have talked about before as a preferred solution.
- Continue to use kuksa.val as that is the only place that contains default tokens for KUKSA Server (Default TLS certs exist in kuksa-common as well)
- Skip submodule dependency and instead use copy/patse

Thoughts @SebastianSchildt ?

**Comment by SebastianSchildt** [comment]
Not sure what the best course of action is, but I thing removing support in python-sdk for val-server could be done immediately, as we still do have released, working versions for val-server out.

The only point is, that this library also works with the VISS "dialect" of databroker, but going forward, I don"t think supporting VISS and GRPC in _one_ library makes sense (especially since API differences can not be hidden, and the current "threaded" API, supporting both, is an ugly compromise). So I would not hink it is worthwhile t kepp that ability (as for "VISS", rather make a nice Node.red Flow in incubation, or see whether the COVESA CSDP webclient works)

**Comment by erikbosch** [comment]
So then it seems @SebastianSchildt  that there is no problem to start by removing default TLS/Token, then we can as a second step decide if we should remove Websocket support or not

**Comment by erikbosch** [comment]
Updated now but should do some more tests

**Comment by erikbosch** [comment]
I have tested pypi package and docker containers, things seems to work. Work might be required in downstream projects if they in test or documentation rely on that tokens/keys/certificates are available locally and default values exist.

**Review by SebastianSchildt — APPROVED** [review]
Looks good. Did some manual checking with latest databroker, seems to work lgtm 🤵

**Pull request merged**
