### PR TITLE
Continuous subscription at a specific frequency

### PR DESCRIPTION
**Pull request by rafaeling**
See https://github.com/eclipse/kuksa.val/pull/734 for more information

Dont forget to update submodules correctly to the one in here: https://github.com/boschglobal/kuksa.val/tree/add_continuous_subscription
it contains the new proto API definition

### CODE REVIEW

**Comment by erikbosch** [comment]
Failure is expected as Databroker submodule isn't updated. For test purposes we could update submodule reference as soon as the change is merge in kuksa.val, but I would prefer if kuksa.val (and Databroker) is released so that we actually can integrate and test towards a release version. I.e. creating a 0.4.2 version of Databroker. As KUKSA Databroker migration is in progress we could decide if the new release should be the last release of the old location, or the first of the new location.

Creating a release/tagged version of Databroker also helps all other repos that maintain local copies of the Proto-files, so that they can refer to they a specific version of the proto files.

With this update it would also be good if we could update the tests, possibly adding one or more test cases to the file below to show that we handle the frequency argument correctly
https://github.com/eclipse-kuksa/kuksa-python-sdk/blob/main/kuksa-client/tests/test_grpc.py

**Comment by lukasmittag** [comment]
do we want to give the cli the ability as well?

**Comment by erikbosch** [comment]
Reopening all PRs closed by accident by boschglobal maintenance

**Comment by erikbosch** [comment]
Converted to draft as it is still is work in progress, correct @rafaeling ?

**Comment by erikbosch** [comment]
@rafaeling - worth keeping?

**Comment by erikbosch** [comment]
No activity for quite some time here. Closing it for now. Please rebase and reopen if needed.

**Pull request closed without merging**
